checks:
  php:
    code_rating: true
    duplication: true
tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
filter:
  excluded_paths:
    - Tests/*
build:
  environment:
    variables:
      SYMFONY_DEPRECATIONS_HELPER: 'max[total]=999999'
  nodes:
    my-tests:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
      environment:
        php: 7.1
